import nodemailer from "nodemailer";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req) {
  try {
    const { name, email, subject, website } = await req.json();

    if (!name || !email) {
      return Response.json(
        { success: false, error: "Name and Email are required" },
        { status: 400 },
      );
    }

    // ✅ Email transporter
    const transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 465,
      secure: true,
      auth: {
        user: "karan.kushel.digisolution@gmail.com",
        pass: "qzkrewyfznhpaojk",
      },
    });

    // ✅ Admin mail
    await transporter.sendMail({
      from: '"System Notification" <karan.kushel.digisolution@gmail.com>',
      to: "karan.kushel.digisolution@gmail.com",
      subject: `🚀 New Lead: ${name} via Contact Form`,
      html: `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
      <div style="background-color: #303030; color: #ffffff; padding: 15px 20px;">
        <h2 style="margin: 0; font-size: 18px;">New Contact Form Submission</h2>
      </div>
      
      <div style="padding: 20px; background-color: #ffffff;">
        <p style="color: #666;">You have received a new inquiry from the website. Here are the details:</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr style="background-color: #f9f9f9;">
            <td style="padding: 12px; border: 1px solid #eee; font-weight: bold; width: 30%;">Full Name:</td>
            <td style="padding: 12px; border: 1px solid #eee;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 12px; border: 1px solid #eee; font-weight: bold;">Email Address:</td>
            <td style="padding: 12px; border: 1px solid #eee;">
              <a href="mailto:${email}" style="color: #0058BE; text-decoration: none;">${email}</a>
            </td>
          </tr>
          <tr style="background-color: #f9f9f9;">
            <td style="padding: 12px; border: 1px solid #eee; font-weight: bold;">Subject:</td>
            <td style="padding: 12px; border: 1px solid #eee;">${subject || "Not Provided"}</td>
          </tr>
          <tr>
            <td style="padding: 12px; border: 1px solid #eee; font-weight: bold;">Message : </td>
            <td style="padding: 12px; border: 1px solid #eee;">
              ${website ? `<a href="${website.startsWith("http") ? website : `https://${website}`}" target="_blank" style="color: #0058BE; text-decoration: none;">${website}</a>` : '<span style="color: #999;">Not Provided</span>'}
            </td>
          </tr>
          <tr style="background-color: #f9f9f9;">
            <td style="padding: 12px; border: 1px solid #eee; font-weight: bold;">Submission Date:</td>
            <td style="padding: 12px; border: 1px solid #eee;">${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}</td>
          </tr>
        </table>
        
        <div style="margin-top: 25px; text-align: center;">
          <a href="mailto:${email}" 
             style="background-color: #FDE105; color: #303030; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
             Reply to Lead
          </a>
        </div>
      </div>
      
      <div style="background-color: #f4f4f4; padding: 15px; text-align: center; font-size: 11px; color: #999;">
        This email was automatically generated by the EDF server.
      </div>
    </div>
  `,
    });

    await transporter.sendMail({
      from: '"EDF" <karan.kushel.digisolution@gmail.com>',
      to: email,
      subject: "We've received your message! – EDF",
      html: `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 12px; overflow: hidden;">
      <div style="background-color: #FDE105; padding: 20px; text-align: center;">
        <h1 style="margin: 0; color: #303030; font-size: 24px;">EDF</h1>
      </div>
      
      <div style="padding: 30px; line-height: 1.6; color: #333333;">
        <h2 style="color: #303030; margin-top: 0;">Hi ${name},</h2>
        <p>Thank you for reaching out to us! We've successfully received your request and our team is already looking into it.</p>
        
        <p>Providing the best customization experience for your website is our top priority. One of our experts will get back to you within <b>24 business hours</b>.</p>
        
        <div style="margin: 30px 0; text-align: center;">
          <a href="edf-three.vercel.appe" 
             style="background-color: #303030; color: #ffffff; padding: 12px 25px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;">
             Explore Our Showcase
          </a>
        </div>
        
        <p style="margin-bottom: 0;">Best Regards,</p>
        <p style="margin-top: 5px; font-weight: bold; color: #303030;">The EDF Team</p>
      </div>
      
      <div style="background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #888888;">
        <p style="margin: 0;">&copy; EDF All rights reserved.</p>
        <p style="margin: 5px 0;">Ghaziabad, Uttar Pradesh, India</p>
      </div>
    </div>
  `,
    });

    return Response.json({
      success: true,
      message: "Form submitted successfully",
    });
  } catch (error) {
    return Response.json(
      { success: false, error: error.message },
      { status: 500 },
    );
  }
}
